### ISSUE TITLE
Trouble to install in 4.6.3

### ISSUE THREAD

**Issue by aszx0413** [Comee/EclipseFormatter#1]
I am using Eclipse PDT Neon.3 Release (4.6.3)
When I tried to install the .jar plugin. An error occured.

`Help`->`Install New Software`->`Add...`->`Archive...`
> Could not find jar:file:/Users/xxx/org.eclipse.jdt.core_3.12.3...

Was I doing something wrong? Hope someone can help. Thanks.

**Comment by Comee** [comment]
1、Eclipse Installer安装的eclipse:
```
下载相应版本的jar包，直接将其拷贝到C:\Users\${currentUser}\.p2\pool\plugins目录中，覆盖原有文件即可
```
2、免安装版本的eclipse:
```
下载相应版本的jar包，直接将其拷贝到 ${installedDirectory}\plugins目录中，覆盖原有文件即可
```
建议使用 [4.7.1a [Oxygen.1a]](https://github.com/Comee/EclipseFormatter/tree/master/4.7.1a%20%5BOxygen.1a%5D)

**Comment by aszx0413** [comment]
适用于Eclipse PDT么

**Comment by Comee** [comment]
你可以测试下，我没测试过

**Comment by aszx0413** [comment]
我测试了不行。Eclipse PDT对于编辑器的代码格式化在`Preferences->PHP->Code Style->Formatter`菜单中设置的，这本身和eclipse就不同。
我尝试把jar包放到plugins下，重启eclipse，但在上述菜单中也没有发现可以设置等号对齐：
<img width="500" alt="qq20171116-134209 2x" src="https://user-images.githubusercontent.com/2009321/32875697-51253c42-cad4-11e7-89f4-0da74cefc8e9.png">

<img width="500" alt="qq20171116-134234 2x" src="https://user-images.githubusercontent.com/2009321/32875706-58d8a776-cad4-11e7-82ef-7e44db8d3e49.png">

**Comment by Comee** [comment]
那应该是不支持。估计用的代码格式化逻辑不是同一块代码。
